/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Main.MenuUtama;
import dao.Daologin;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Modellogin;
import service.Servicelogin;

/**
 *
 * @author ACER
 */
public class MenuLogin extends javax.swing.JFrame {
    int xx, xy;
    
    private Servicelogin servis = new Daologin();

    /**
     * Creates new form Menu_Login
     */
    public static boolean tutup = false;
    
    public MenuLogin() {
        initComponents();
        
        bt_login.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void bersih(){
        t_username.setText("Username");
        t_pass.setText("Password");
//        t_level.setText("");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name_gui = new javax.swing.JTextField();
        bt_pilih = new javax.swing.JComboBox<>();
        t_username = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        bt_exit = new javax.swing.JLabel();
        bg_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 76), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_pass.setText("Password");
        t_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 76), 1, true));
        t_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_passFocusLost(evt);
            }
        });
        t_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passActionPerformed(evt);
            }
        });
        t_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passKeyPressed(evt);
            }
        });
        jPanel1.add(t_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\male_user_20px.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\password_key_20px.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 30, 30));

        Name_gui.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        Name_gui.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name_gui.setText("FORM LOGIN");
        Name_gui.setBorder(null);
        Name_gui.setFocusable(false);
        jPanel1.add(Name_gui, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 190, 40));

        bt_pilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siswa", "Guru", "Admin" }));
        bt_pilih.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        bt_pilih.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_pilih.setFocusable(false);
        bt_pilih.setLightWeightPopupEnabled(false);
        bt_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pilihActionPerformed(evt);
            }
        });
        jPanel1.add(bt_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 80, 30));

        t_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_username.setText("Username");
        t_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 76), 1, true));
        t_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        t_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_usernameFocusLost(evt);
            }
        });
        jPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 30));

        bt_login.setBackground(new java.awt.Color(110, 217, 161));
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("LOGIN");
        bt_login.setBorder(null);
        bt_login.setBorderPainted(false);
        bt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_login.setFocusable(false);
        bt_login.setPreferredSize(new java.awt.Dimension(64, 18));
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_loginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_loginMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bt_loginMouseReleased(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        jPanel1.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 100, 30));

        bt_exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Pictures\\logout_20px.png")); // NOI18N
        bt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exitMouseClicked(evt);
            }
        });
        jPanel1.add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 20, 30));

        bg_login.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\Background Login.png")); // NOI18N
        bg_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 155, 76), 1, true));
        jPanel1.add(bg_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        setSize(new java.awt.Dimension(840, 440));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exitMouseClicked
        dispose();
        System.exit(0);
    }//GEN-LAST:event_bt_exitMouseClicked

    private void t_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passActionPerformed

    private void bt_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseEntered
        bt_login.setBackground((new Color(97,204,148)));
    }//GEN-LAST:event_bt_loginMouseEntered

    private void bt_loginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMousePressed
        xx = evt.getX();
        xy = evt.getY();
        
        bt_login.setBackground((new Color(85,192,136)));
    }//GEN-LAST:event_bt_loginMousePressed

    private void bt_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseExited
        bt_login.setBackground((new Color(110,217,161)));
    }//GEN-LAST:event_bt_loginMouseExited

    private void bt_loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseReleased
        bt_login.setBackground((new Color(110,217,161)));
    }//GEN-LAST:event_bt_loginMouseReleased

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        proseslogin();
        
        dispose();
    }//GEN-LAST:event_bt_loginActionPerformed

    private void t_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusGained
        String user=t_username.getText();
        if(user.equals("Username")){
            t_username.setText("");
        }
    }//GEN-LAST:event_t_usernameFocusGained

    private void t_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_usernameFocusLost
        String user=t_username.getText();
        if(user.equals("")||user.equals("Username")){
            t_username.setText("Username");

        }
    }//GEN-LAST:event_t_usernameFocusLost

    private void t_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passFocusGained
        String pass=t_pass.getText();
        if(pass.equals("Password")){
            t_pass.setText("");
        }
    }//GEN-LAST:event_t_passFocusGained

    private void t_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_passFocusLost
        String pass=t_pass.getText();
        if(pass.equals("")||pass.equals("Password")){
            t_pass.setText("Password");
        }
    }//GEN-LAST:event_t_passFocusLost

    private void t_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            bt_login.doClick();
        }
    }//GEN-LAST:event_t_passKeyPressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void bt_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pilihActionPerformed
        
    }//GEN-LAST:event_bt_pilihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name_gui;
    private javax.swing.JLabel bg_login;
    private javax.swing.JLabel bt_exit;
    private javax.swing.JButton bt_login;
    private javax.swing.JComboBox<String> bt_pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables

    private void proseslogin() {
        if(validasiInput()==true){
            String id = t_username.getText();
            String user = t_username.getText();
            String pass = t_pass.getText();
            
            Modellogin modlogin = new Modellogin();
            
            modlogin.setID_pengguna(id);
            modlogin.setUsername(user);
            modlogin.setPassword(pass);
            
            servis.proseslogin(modlogin);
            if(tutup){
                dispose();
            }
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if(t_username.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        }else if(t_pass.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }
}
